---
- name: Teatplaybook for custom module
  gather_facts: False
  hosts: 
      - dns_servers
  tasks: 
    # - name: test custom module
    #   delegate_to: localhost
    #   absible_barn:
    #     host: "192.168.1.39"
    #     name: "{{inventory_hostname}}"
    #     user: "admin-user"
    #     password: "jfldmdpdeiehjkHGSthjjhDdfghhFdf"
    #     port: 9200
    #     state: present
    #     data: 
    #       test: data
    #       creationdate: vandaag
    #   register: output
    - name: ansible barn 2 test
      ansible_barn:
        host: "192.168.56.3"
        name: "{{inventory_hostname}}"
        barn_type: "mongodb"
        user: "admin-user"
        password: "jfldmdpdeiehjkHGSthjjhDdfghhFdf"
        port: 27017
        state: absent
        data: 
          test: data2
          creationdate: vandaag
      delegate_to: localhost
      register: output
    - name: debug
      debug: 
        var: "output"