---
- name: Teatplaybook for custom module
  gather_facts: False
  hosts: 
      - srvdns01.myhomecloud.be
  tasks: 
    - name: ansible barn 2 test
      throttle: 1
      barn_read:
        host: "127.0.0.1"
        user: "sdescamps"
        password: "testpassword"
        port: 5000
        state: absent
        data: 
          test: data2
          creationdate: vandaag
      delegate_to: localhost
      register: output
    - name: debug
      debug: 
        var: "output"