---
- name: Test playbook for custom module
  gather_facts: False
  hosts: 
      - testhost.myhomecloud.be
  tasks:
    - name: barn write
      barn_write:
        barn_host: "127.0.0.1"
        barn_user: "sdescamps"
        barn_password: "testpassword"
        barn_port: 5000
        state: present
        vars: 
          test: sdqf
          creationdate: vandaag
        remove_vars: 
          - "something_which_not_exists"
          - to_remove
      register: output 
    - name: output barn write
      debug: 
        var: "output"
    
    - name: barn read
      barn_read:
        barn_host: "127.0.0.1"
        barn_user: "sdescamps"
        barn_password: "testpassword"
        barn_port: 5000
      delegate_to: localhost
      register: output

    - name: output barn read
      debug: 
        var: "output"

    - name: Remove new host
      barn_write:
        barn_host: "127.0.0.1"
        barn_user: "sdescamps"
        barn_password: "testpassword"
        barn_port: 5000
        state: absent
      register: output 

    - name: Output host removal
      debug: 
        var: "output"
     
    - name: print facts
      debug: 
        var: hostvars[inventory_hostname]