get:
  summary: Get list of hosts
  security:
    - basicAuth: []
  parameters:
      - in: query
        name: name
        schema:
          type: string
        required: false
        description: search on name of node
      - in: query
        name: parrent_vars
        schema:
          type: string
        required: false
        description: (under construction) Return also the vars from the host its groups
  responses:
    "200":
      $ref: './swagger.yml#/components/responses/DefaultResponse'
    '401':
      $ref: './swagger.yml#/components/responses/UnauthorizedError'
post:
  summary: Returns list of hosts
  security:
    - basicAuth: []
  parameters:
      - in: query
        name: name
        schema:
          type: string
        required: false
        description: search on name of node
      - in: query
        name: parrent_vars
        schema:
          type: string
        required: false
        description: (under construction) Return also the vars from the host its groups 
  requestBody:
    required: false
    content:
      application/json:
        schema:
          type: object
          properties:
            name:
              title: Name of the host
              type: string
              description: Name of the Host
            groups:
              type: array
              items:
                type: string
              description: (under construction) Return all hosts which belong to a given list of groups
            vars:
              type: object
              description: (under construction) Return all hosts which have specific variables
  responses:
    "200":
      $ref: './swagger.yml#/components/responses/DefaultResponse'
    '401':
      $ref: './swagger.yml#/components/responses/UnauthorizedError'
put:
  summary: Add/Update host
  security:
    - basicAuth: []
  requestBody:
    required: false
    content:
      application/json:
        schema:
          type: object
          properties:
            name:
              title: Name of the host
              type: string
              description: Name of the Host
            groups:
              type: array
              items:
                type: string
              description: "Alias for 'groups_present'"
            groups_present:
              type: array
              items:
                type: string
              description: Ensures that host belongs to the groups. Keeps the already assigned groups. 
            groups_absent:
              type: array
              items:
                type: string
              description: Removes host form groups
            groups_set:
              type: array
              items:
                type: string
              description: Host only belongs to the given groups. Mutually exclusive with groups, groups_present, groups_absent 
            create_groups:
              type: boolean
              default: true
              description: When an unexisting group is configured it will be created. 
            vars:
              type: object
              description: Variables to add or update
            vars_absent:
              type: array
              description: Removes variables from host
              items:
                type: string
          required:
            - name
  responses:
    "200":
      $ref: './swagger.yml#/components/responses/DefaultResponse'
    '401':
      $ref: './swagger.yml#/components/responses/UnauthorizedError'