get:
  summary: Get list of hosts
  tags:
    - inventory
  security:
    - basicAuth: []
  parameters:
      - in: query
        name: name
        schema:
          type: string
        required: false
        description: Filter on name of host. Use '*' as a wildcard.
      - in: query
        name: regex
        schema:
          type: boolean
        required: false
        description: Name is regular expression
      - in: query
        name: parent_vars
        schema:
          type: string
        required: false
        description: (under construction) Return also the vars from the host its groups
  responses:
    "200":
      $ref: './swagger.yml#/components/responses/DefaultResponse'
    '401':
      $ref: './swagger.yml#/components/responses/UnauthorizedError'
post:
  summary: Returns list of hosts
  tags:
    - inventory
  security:
    - basicAuth: []
  requestBody:
    required: false
    content:
      application/json:
        schema:
          type: object
          properties:
            name:
              title: Name of the host
              type: string
              description: Name of the Host
            regex:
              title: Name is regular expression
              type: boolean
              description: The name is a regular expression. The regular expression need to match the entire name. 
            groups:
              type: array
              items:
                type: string
              description: (under construction) Return all hosts which belong to a given list of groups
            vars:
              type: object
              description: (under construction) Return all hosts which have specific variables
  responses:
    "200":
      $ref: './swagger.yml#/components/responses/DefaultResponse'
    '401':
      $ref: './swagger.yml#/components/responses/UnauthorizedError'
put:
  summary: Add/Update host
  description: See /api/v1/inventory/hosts/present for more details
  tags:
    - inventory