version: '3'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin-user
            MONGO_INITDB_ROOT_PASSWORD: jfldmdpdeiehjkHGSthjjhDdfghhFdf
            MONGO_INITDB_DATABASE: inventory
        ports:
            - 27017-27019:27017-27019
        volumes:
            - ./mongodb/src/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - ./mongodb/mongo-volume:/data/db
    barn:
        image: barn:latest
        container_name: barn
        build:
            context: ./barn/
            dockerfile: ./Dockerfile
        links:
            - mongodb
        restart: always
        ports:
            - "5000:5000"