version: '3.1'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin-user
            MONGO_INITDB_ROOT_PASSWORD: jfldmdpdeiehjkHGSthjjhDdfghhFdf
            MONGO_INITDB_DATABASE: inventory
        ports:
            - 27017-27019:27017-27019
        volumes:
            - ./mongodb/src/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - ./mongodb/mongo-volume:/data/db
        networks:
            - barn_network
    barn_api:
        image: barn:latest
        build:
            context: ./barn/
            dockerfile: ./Dockerfile
        links:
            - mongodb
        restart: always
        environment:
            - PYTHONUNBUFFERED=1
        ports:
            - "5000:5000"
        networks:
            - barn_network
    nginx:
        image: nginx:latest
        container_name: reverse_proxy
        volumes:
            - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
        #     - ./nginx/cert/barn.myhomecloud.be.pem:/etc/nginx/cert/barn.pem
            - ./nginx/cert/barn.myhomecloud.be.key:/etc/nginx/cert/barn.key
            - ./nginx/cert/barn.myhomecloud.be.crt:/etc/nginx/cert/barn.crt
        ports:
            - 80:80
            - 443:443
        links:
            - barn_api
        networks:
            - barn_network
networks:
    barn_network:

